### ISSUE TITLE
Not working after 1st tournamemt

### ISSUE THREAD

**Issue by negroscuro** [prof18/Friends-Tournament#4]
Hello,
I was looking for a software to play xwing tournemts and I found your app pretty useful
The problem is I did a test tournemt amd now i cannot create a real/new one sonce it get stucked at the very end of the creation ...
It would be really nice if you add the posibility of brackets/cut after the rounds.
Cheers

**Comment by negroscuro** [comment]
I did 13 players, 3 rounds for matches of two persons...

**Comment by prof18** [comment]
Thank you very much for reporting this and sorry for the very late reply. Anyway, I fixed the issue and it will be released in the  next days/weeks
